### ISSUE TITLE
RequestPermissionsAsync returns Denied directly if users denied the first time

### ISSUE THREAD

**Issue by hs79hs** [jamesmontemagno/PermissionsPlugin#172]
Hi, by my tests, if a user denied RequestPermissionsAsync at the first time, after that, it will always directly return Denied, won't show requests again. 

Only if I reinstalled APP, RequestPermissionsAsync will show requests again.

Am I right? If so, I don't think that's a good idea because users may change their mind after knowing why we need those permissions.

**Comment by ngalicoco** [comment]
@hs79hs as far as I know on Operating system will not display that permission request prompt if user decides to Deny (iOS Deny, Android deny and user selects don't show this prompt again). In that case we know that user denied the permission and take them to app settings to re-enable (iOS Ask Next Time, Android allow). This has been the same behavior at least for two years, since we started using this plugin for location and other native permissions. I don't think it is an issue with this plugin, it is the operating system functionality. Hope this helps.

**Comment by jamesmontemagno** [comment]
You only have 1 chance with iOS and then it will never open again. That is how iOS works :(
